[book]
title = "The Calyxium Programming Language"
authors = ["Codezz-ops", "Crab-K1ng", "Spicylemon"]
language = "en"

[output.html]
git-repository-url = "https://github.com/Calyxium-Lang/book"
additional-js = ["js/menu-title-link.js"]

[preprocessor.random]
command = "python run_tests.py"

[calyxium]
edition = "2025"