name: Deploy book to parent

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout book repo
        uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'

      - name: Build mdBook
        run: |
          mdbook build
      
      - name: Deploy to Parent Repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git clone https://x-access-token:${{ secrets.PARENT_REPO_TOKEN }}@github.com/calyxium-lang/calyxium-lang.github.io.git parent-repo
          
          # Remove old docs and copy new build
          rm -rf parent-repo/docs
          mkdir -p parent-repo/docs
          cp -r book/* parent-repo/docs/

          cd parent-repo
          git add .
          git commit -m "Update book"
          git push
